import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import base64
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "scikit-learn"], check=True)
from sklearn.ensemble import HistGradientBoostingClassifier

BASE = Path(__file__).resolve().parent

st.set_page_config(
    page_title="CFL Play Frequency Outliers",
    page_icon="🏈",
    layout="wide",
    initial_sidebar_state="expanded"
)

TEAM_COLORS = {
    "BC":  {"bg": "#F97316", "fg": "#FFFFFF"},
    "CGY": {"bg": "#D32F2F", "fg": "#FFFFFF"},
    "EDM": {"bg": "#F4C542", "fg": "#111111"},
    "HAM": {"bg": "#111111", "fg": "#F4C542"},
    "MTL": {"bg": "#0B1F4D", "fg": "#FFFFFF"},
    "OTT": {"bg": "#C62828", "fg": "#FFFFFF"},
    "SSK": {"bg": "#2E7D32", "fg": "#FFFFFF"},
    "TOR": {"bg": "#1976D2", "fg": "#FFFFFF"},
    "WPG": {"bg": "#003F87", "fg": "#FFFFFF"},
}
TEAM_NAMES = {
    "BC":  "BC Lions",          "CGY": "Calgary Stampeders",
    "EDM": "Edmonton Elks",     "HAM": "Hamilton Tiger-Cats",
    "MTL": "Montreal Alouettes","OTT": "Ottawa REDBLACKS",
    "SSK": "Saskatchewan Roughriders",
    "TOR": "Toronto Argonauts", "WPG": "Winnipeg Blue Bombers",
}
TEAM_LOGOS = {
    "BC":  "assets/logos/BC.png",  "CGY": "assets/logos/cal.png",
    "EDM": "assets/logos/edm.png", "HAM": "assets/logos/Ham.png",
    "MTL": "assets/logos/mtl.png", "OTT": "assets/logos/Ott.png",
    "SSK": "assets/logos/ssk.png", "TOR": "assets/logos/Tor.png",
    "WPG": "assets/logos/wpg.png",
}

def get_logo_path(team_code):
    p = BASE / TEAM_LOGOS.get(team_code, "")
    return p if p.exists() else None

@st.cache_resource
def load_model():
    """Train the model from raw data at startup — no pkl, no version mismatch."""
    data_path = BASE / "CFL_PLAY_BY_PLAY.xlsx"
    df = pd.read_excel(data_path)
    df = df[df["play_type"].isin(["Pass", "Run", "Sack"])].copy()
    df["called_pass"] = np.where(df["play_type"].isin(["Pass", "Sack"]), 1, 0)

    df["away_team"] = df["game"].str.extract(r"- (\w+) @")
    df["home_team"] = df["game"].str.extract(r"@ (\w+)")
    df["score_diff_offense"] = np.where(
        df["possession_team"] == df["home_team"],
        df["home_team_score"] - df["away_team_score"],
        df["away_team_score"] - df["home_team_score"],
    )

    df["yards_to_go"]               = df["yards_to_go"].fillna(df["yards_to_go"].median())
    df["yards_to_endzone"]          = df["yards_to_endzone"].fillna(df["yards_to_endzone"].median())
    df["seconds_in_half_remaining"] = df["seconds_in_half_remaining"].fillna(df["seconds_in_half_remaining"].median())
    df["defensive_team"]            = df["defensive_team"].fillna("UNK")
    df["down_x_yards"]              = df["down"] * df["yards_to_go"]
    df["is_2nd_short"]              = ((df["down"] == 2) & (df["yards_to_go"] <= 3)).astype(int)
    df["garbage_time"]              = ((df["score_diff_offense"].abs() > 20) & (df["seconds_in_half_remaining"] < 600)).astype(int)
    df["leading_late"]              = ((df["score_diff_offense"] > 7) & (df["seconds_in_half_remaining"] < 300)).astype(int)
    df["two_min_trailing"]          = ((df["seconds_in_half_remaining"] <= 120) & (df["score_diff_offense"] < 0)).astype(int)

    le_off = LabelEncoder()
    le_def = LabelEncoder()
    df["possession_team_enc"] = le_off.fit_transform(df["possession_team"])
    df["defensive_team_enc"]  = le_def.fit_transform(df["defensive_team"])

    features = [
        "possession_team_enc", "defensive_team_enc",
        "quarter", "down", "yards_to_go", "yards_to_endzone",
        "seconds_in_half_remaining", "score_diff_offense",
        "down_x_yards", "is_2nd_short", "garbage_time",
        "leading_late", "two_min_trailing",
    ]

    df_clean = df.dropna(subset=features + ["called_pass"])
    X = df_clean[features]
    y = df_clean["called_pass"]

    model = HistGradientBoostingClassifier(
        max_iter=500, max_depth=6, learning_rate=0.04,
        min_samples_leaf=12, l2_regularization=0.5,
        class_weight="balanced", random_state=42,
        early_stopping=True, validation_fraction=0.1, n_iter_no_change=25,
    )
    model.fit(X, y)

    return {
        "model":         model,
        "le_offense":    le_off,
        "le_defense":    le_def,
        "features":      features,
        "offense_teams": le_off.classes_.tolist(),
        "defense_teams": le_def.classes_.tolist(),
    }

@st.cache_data
def load_team_lookup():
    return pd.read_csv(BASE / "cfl_team_bucket_lookup.csv")

@st.cache_data
def load_comparables():
    return pd.read_csv(BASE / "cfl_historical_comparables_v2.csv")

@st.cache_data
def load_metrics():
    with open(BASE / "cfl_model_metrics_v2.json", "r") as f:
        return json.load(f)

@st.cache_data
def load_tendencies():
    """Pre-computed tendencies — generated by precompute_tendencies.py"""
    p = BASE / "cfl_top5_tendencies_precomputed.csv"
    if p.exists():
        return pd.read_csv(p)
    return None

MODEL_PKG = load_model()
MODEL     = MODEL_PKG["model"]
LE_OFF    = MODEL_PKG["le_offense"]
LE_DEF    = MODEL_PKG["le_defense"]
FEATURES  = MODEL_PKG["features"]
OFF_TEAMS = MODEL_PKG["offense_teams"]
DEF_TEAMS = MODEL_PKG["defense_teams"]

TEAM_LOOKUP = load_team_lookup()
COMPS       = load_comparables()
METRICS     = load_metrics()
TENDENCIES  = load_tendencies()

TEAMS = sorted(TEAM_LOOKUP["possession_team"].dropna().astype(str).unique().tolist())


# ─── Bucket helpers ────────────────────────────────────────────────────────────
def distance_bucket(x):
    if x <= 3:  return "Short (1-3)"
    if x <= 7:  return "Medium (4-7)"
    return "Long (8+)"

def field_bucket(x):
    if x <= 20: return "Red Zone"
    if x <= 40: return "Opponent Territory"
    if x <= 60: return "Midfield"
    if x <= 80: return "Own Territory"
    return "Own Deep"

def score_bucket(x):
    if x <= -8: return "Trailing 8+"
    if x <= -1: return "Trailing 1-7"
    if x == 0:  return "Tied"
    if x <= 7:  return "Leading 1-7"
    return "Leading 8+"

def time_bucket(sec_half):
    if sec_half <= 120: return "2-min"
    if sec_half <= 600: return "Late Half"
    return "Early Half"

def half_seconds(quarter, mins, secs):
    rem = int(mins) * 60 + int(secs)
    return rem + 900 if int(quarter) in (1, 3) else rem

def yards_to_endzone(side, yardline):
    y = float(yardline)
    return 110 - y if side == "Own" else y

def encode_team(le, team, fallback_idx=0):
    """Safely encode a team — use first class if unseen."""
    if team in le.classes_:
        return int(le.transform([team])[0])
    return fallback_idx


# ─── Feature vector ────────────────────────────────────────────────────────────
def build_feature_row(team, def_team, quarter, mins, secs, down, ytg, side, ball_on, score_diff):
    yte      = yards_to_endzone(side, ball_on)
    sec_half = half_seconds(quarter, mins, secs)

    row = {
        "possession_team_enc":      encode_team(LE_OFF, team),
        "defensive_team_enc":       encode_team(LE_DEF, def_team),
        "quarter":                  quarter,
        "down":                     down,
        "yards_to_go":              ytg,
        "yards_to_endzone":         yte,
        "seconds_in_half_remaining": sec_half,
        "score_diff_offense":       score_diff,
        "down_x_yards":             down * ytg,
        "is_2nd_short":             int(down == 2 and ytg <= 3),
        "garbage_time":             int(abs(score_diff) > 20 and sec_half < 600),
        "leading_late":             int(score_diff > 7 and sec_half < 300),
        "two_min_trailing":         int(sec_half <= 120 and score_diff < 0),
    }
    return pd.DataFrame([row])[FEATURES], yte, sec_half


# ─── Bucket lookup ─────────────────────────────────────────────────────────────
def get_bucket_lookup(team, down, ytg, yte, score_diff, sec_half):
    tb = distance_bucket(ytg); fb = field_bucket(yte)
    sb = score_bucket(score_diff); tmb = time_bucket(sec_half)
    sub = TEAM_LOOKUP[
        (TEAM_LOOKUP["possession_team"] == team) &
        (TEAM_LOOKUP["down"] == down) &
        (TEAM_LOOKUP["distance_bucket"] == tb) &
        (TEAM_LOOKUP["field_bucket"] == fb) &
        (TEAM_LOOKUP["score_bucket"] == sb) &
        (TEAM_LOOKUP["time_bucket"] == tmb)
    ]
    if sub.empty: return None
    return sub.sort_values("plays", ascending=False).iloc[0].to_dict()


# ─── Comparables ───────────────────────────────────────────────────────────────
def get_comparables(team, quarter, down, ytg, yte, sec_half, score_diff, top_n=10):
    d = COMPS[(COMPS["possession_team"] == team) & (COMPS["down"] == down)].copy()
    if d.empty: return d
    d["distance_score"] = (
        ((d["quarter"] - quarter) / 2.0) ** 2 +
        ((d["yards_to_go"] - ytg) / 4.0) ** 2 +
        ((d["yards_to_endzone"] - yte) / 15.0) ** 2 +
        ((d["seconds_in_half_remaining"] - sec_half) / 240.0) ** 2 +
        ((d["score_diff_offense"] - score_diff) / 7.0) ** 2
    )
    d = d.sort_values("distance_score").head(top_n).copy()
    d["called_play"] = np.where(d["called_pass"] == 1, "Pass", "Run")
    return d[["cfl_game_id","play_id","called_play","play_result","description",
              "quarter","yards_to_go","yards_to_endzone","seconds_in_half_remaining",
              "score_diff_offense","distance_score"]]


# ─── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
.block-container { padding-top:1rem; padding-bottom:1rem; }
.banner-shell {
    background: linear-gradient(180deg,#0f172a 0%,#111827 100%);
    border:1px solid #1f2937; border-radius:22px;
    padding:20px 22px; margin-bottom:1rem;
}
.banner-title  { color:white; font-size:2rem; font-weight:800; line-height:1.05; margin-bottom:.45rem; }
.banner-subtitle { color:#cbd5e1; font-size:1rem; }
.banner-team-name { color:white; font-size:1.5rem; font-weight:800; text-align:right; }
.banner-team-label { color:#94a3b8; font-size:.9rem; text-align:right; margin-top:.35rem; }
div[data-testid="stMetric"] {
    background:#f8fafc; border:1px solid #e2e8f0;
    padding:10px 14px; border-radius:16px;
}
div[data-testid="stMetric"] label,
div[data-testid="stMetric"] [data-testid="stMetricLabel"] { color:#334155 !important; }
div[data-testid="stMetric"] [data-testid="stMetricValue"] { color:#0f172a !important; font-weight:700 !important; }
</style>
""", unsafe_allow_html=True)

# ─── Session defaults ──────────────────────────────────────────────────────────
defaults = dict(team="WPG", def_team="MTL", quarter=1, minutes=4, seconds=0,
                down=1, ytg=10.0, field_side="Own", ball_on=30.0, score_diff=-10)
for k, v in defaults.items():
    st.session_state.setdefault(k, v)

# ─── Banner ────────────────────────────────────────────────────────────────────
team = st.session_state["team"]
logo_path = get_logo_path(team)
st.markdown('<div class="banner-shell">', unsafe_allow_html=True)
c1, c2, c3 = st.columns([1.6, 0.7, 1.1])
with c1:
    st.markdown('<div class="banner-title">CFL Play Frequency Outliers</div>' +
                '<div class="banner-subtitle">A data-driven model used to anticipate offensive tendencies.</div>',
                unsafe_allow_html=True)
with c2:
    if logo_path: st.image(str(logo_path), width=110)
with c3:
    st.markdown(f'<div class="banner-team-name">{TEAM_NAMES.get(team, team)}</div>' +
                '<div class="banner-team-label">Selected scouting profile</div>',
                unsafe_allow_html=True)
st.markdown('</div>', unsafe_allow_html=True)

# ─── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Game Inputs")
    st.selectbox("Offense team",    TEAMS,           key="team")
    st.selectbox("Defense team",    TEAMS,           key="def_team")  # NEW
    st.selectbox("Quarter",         [1,2,3,4],       key="quarter")
    st.number_input("Minutes left", 0, 15, step=1,   key="minutes")
    st.number_input("Seconds left", 0, 59, step=1,   key="seconds")
    st.selectbox("Down",            [1,2,3],         key="down")
    st.number_input("Yards to go",  0.0, 50.0, step=1.0, key="ytg")
    st.selectbox("Ball side",       ["Own","Opp"],   key="field_side")
    st.number_input("Ball on",      1.0, 55.0, step=1.0, key="ball_on")
    st.number_input("Score diff (offense)", -60, 60, step=1, key="score_diff")
    st.caption("Negative = offense trailing")

    if st.session_state["down"] == 3:
        st.warning("⚠️ 3rd down in the CFL is typically a kicking situation. "
                   "Run/pass probabilities may not be meaningful here.")

# ─── Read inputs ───────────────────────────────────────────────────────────────
team       = st.session_state["team"]
def_team   = st.session_state["def_team"]
quarter    = st.session_state["quarter"]
minutes    = st.session_state["minutes"]
seconds    = st.session_state["seconds"]
down       = st.session_state["down"]
ytg        = float(st.session_state["ytg"])
field_side = st.session_state["field_side"]
ball_on    = float(st.session_state["ball_on"])
score_diff = int(st.session_state["score_diff"])

# ─── Predict ───────────────────────────────────────────────────────────────────
x, yte, sec_half = build_feature_row(
    team, def_team, quarter, minutes, seconds, down, ytg, field_side, ball_on, score_diff
)
pass_prob = float(MODEL.predict_proba(x)[0, 1])
run_prob  = 1 - pass_prob

lookup = get_bucket_lookup(team, down, ytg, yte, score_diff, sec_half)
comps  = get_comparables(team, quarter, down, ytg, yte, sec_half, score_diff)

# ─── Top metrics ───────────────────────────────────────────────────────────────
m1, m2, m3, m4 = st.columns(4)
m1.metric("Pass probability",  f"{pass_prob:.1%}")
m2.metric("Run probability",   f"{run_prob:.1%}")
m3.metric("Model accuracy",    f"{METRICS['accuracy_at_0_5_threshold']:.1%}")
m4.metric("Bucket sample",     f"{int(lookup['plays']) if lookup else 0}")

# ─── Main content ──────────────────────────────────────────────────────────────
left, right = st.columns([1.02, 0.98])

with left:
    st.subheader("Situation snapshot")
    s1,s2,s3,s4 = st.columns(4)
    s1.info(f"**Distance**\n\n{distance_bucket(ytg)}")
    s2.info(f"**Field**\n\n{field_bucket(yte)}")
    s3.info(f"**Score**\n\n{score_bucket(score_diff)}")
    s4.info(f"**Time**\n\n{time_bucket(sec_half)}")

    st.subheader("Model vs team historical average")
    if lookup is not None:
        team_hist_rate = float(lookup["pass_prob_hist"])
        delta_vs_team  = pass_prob - team_hist_rate
        league_rate    = float(lookup["league_pass_prob_hist"])
        delta_vs_league= float(lookup["pass_prob_delta_vs_league"])  # team vs league (historical)
        team_plays     = int(lookup["plays"])
        league_plays   = int(lookup["league_plays"])

        a, b, c = st.columns(3)
        a.metric("Model pass probability",        f"{pass_prob:.1%}")
        b.metric("This team in this bucket",      f"{team_hist_rate:.1%}",
                 help="Historical pass rate for this team in this exact situation bucket")
        c.metric("Team vs league (historical)",   f"{delta_vs_league:+.1%}",
                 help="How this team\'s historical pass rate compares to league average in this bucket")
        st.caption(
            f"**How to read this:** The model predicts {pass_prob:.1%} pass probability. "
            f"Historically, {team} has passed {team_hist_rate:.1%} in similar situations, "
            f"vs the league average of {league_rate:.1%} — a {delta_vs_league:+.1%} tendency. "
            f"(Sample: {team_plays} team plays, {league_plays} league plays)"
        )
    else:
        st.warning("No exact historical bucket match found for this situation.")

    st.subheader("Tendency alert")
    if lookup is not None:
        delta = float(lookup["pass_prob_delta_vs_league"])
        if   delta >=  0.20: st.warning(f"Pass-heavy outlier: {team} passes {delta:+.1%} vs league average in this bucket.")
        elif delta <= -0.20: st.warning(f"Run-heavy outlier: {team} passes {delta:+.1%} vs league average in this bucket.")
        else:                st.info("No major outlier. This team is within ±20% of league average in this situation.")
    else:
        st.info("No league comparison available for this exact situation bucket.")

with right:
    st.subheader("Live scenario summary")
    st.markdown(f"""
**Offense:** {team} vs **Defense:** {def_team}  
**Game state:** Q{quarter}, {minutes}:{str(seconds).zfill(2)} left  
**Situation:** {down} & {ytg:g} at {field_side.lower()} {ball_on:g}  
**Score diff (offense):** {score_diff:+d}  
**Derived yards_to_endzone:** {yte:.1f}  
**Derived seconds_in_half_remaining:** {sec_half}
""")

    st.subheader("Closest historical comparables")
    if comps.empty:
        st.warning("No comparables found for this team/down combination.")
    else:
        view = comps.copy()
        view["distance_score"] = view["distance_score"].round(3)
        st.dataframe(view, use_container_width=True, height=430)

st.divider()

# ─── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2 = st.tabs(["Top 5 Tendencies Per Team", "Model Details"])

with tab1:
    st.subheader("Top 5 high-confidence tendencies per team")
    if TENDENCIES is not None:
        st.caption("Pre-computed from the full 2024 season. Situations where a team deviates ≥20% from league average with ≥10 team plays and ≥20 league plays.")
        top5 = TENDENCIES.groupby("team", group_keys=False).head(5).copy()
        for col in ["delta_vs_league","model_pass_prob","league_pass_rate"]:
            if col in top5.columns:
                top5[col] = top5[col].map(lambda x: f"{float(x):+.1%}" if "delta" in col else f"{float(x):.1%}")
        st.dataframe(top5, use_container_width=True, height=520)
        csv = TENDENCIES.groupby("team", group_keys=False).head(5).to_csv(index=False).encode()
        st.download_button("Download CSV", csv, "cfl_top5_tendencies.csv", "text/csv")
    else:
        st.info("Run `python precompute_tendencies.py` once to generate this table, "
                "then add `cfl_top5_tendencies_precomputed.csv` to the app folder.")

with tab2:
    st.subheader("Model details — v2")
    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("**Performance metrics**")
        st.markdown(f"""
| Metric | v2 (new) | v1 (old) |
|---|---|---|
| Accuracy | {METRICS['accuracy_at_0_5_threshold']:.1%} | 71.5% |
| ROC-AUC | {METRICS.get('roc_auc', 0):.3f} | ~0.76 est. |
| Log Loss | {METRICS['log_loss']:.4f} | 0.5300 |
| Test split | Game-based | Random rows |
""")
    with col_b:
        st.markdown("**What changed in v2**")
        for item in METRICS.get("v1_comparison", {}).get("key_improvements", []):
            st.markdown(f"✅ {item}")

    with st.expander("Full model spec"):
        st.markdown(f"""
- **Model:** {METRICS['model_type']}
- **Features:** {", ".join(METRICS['features_used'])}
- **Rows modeled:** {METRICS['overall_rows_modeled']:,}
- **Train games:** {METRICS['train_games']} | **Test games:** {METRICS['test_games']}
- **Target:** {METRICS['target_definition']}
- **Split method:** {METRICS['split_method']}
""")
